Disable some menu items in read-only mode
siyuan-note/siyuan pull request #11733
Opened 2024-06-15 14:23 UTC by Zuoqiu-Yingyi

* [x] Please commit to the dev branch
* [ ] For contributing new features, please supplement and improve the corresponding user guide documents
* [ ] For bug fixes, please describe the problem and solution via code comments
* [ ] For text improvements (such as typos and wording adjustments), please submit directly

REL: #11367 #11707

在内核只读模式 & 发布模式下禁用会导致 `Forbidden` 提示的菜单项

2024-06-15 16:10 UTC, 88250 commented
提交完了可以 review 的时候说一声，谢谢。

2024-06-15 16:15 UTC, Zuoqiu-Yingyi commented
> 提交完了可以 review 的时候说一声，谢谢。

可以 review 了

2024-06-16 01:27 UTC, 88250 commented on kernel/api/setting.go
> -	if !model.IsAdminRoleContext(c) {
这里删了前端没跟着改的话会报错 403

2024-06-16 01:28 UTC, 88250 approved these changes

2024-06-17 01:52 UTC, Vanessa219 requested changes
请进行相关修改

2024-06-17 01:52 UTC, Vanessa219 commented on app/src/config/editor.ts
> +                if (response.code === 0) {
@88250 修改过后台请求处理，为保持所有请求的一致性处理，这个没有其他情况的话请不要进行修改。

2024-06-17 01:52 UTC, Vanessa219 commented on app/src/index.ts
> +        addScriptSync(`${Constants.PROTYLE_CDN}/js/lute/lute.min.js?v=${Constants.SIYUAN_VERSION}`, "protyleLuteScript"),
这一块比较复杂，没有必要请不要进行改动。如有必要的话请只修改关联部分即可。

2024-06-17 01:52 UTC, Vanessa219 commented on app/src/menus/commonMenuItem.ts
> +                        } else if (response.code === 0) {
修改参见第一条

2024-06-17 01:52 UTC, Vanessa219 commented on app/src/mobile/index.ts
> +        addBaseURL();
请参见第二点进行修改

2024-06-17 01:52 UTC, Vanessa219 commented on app/src/protyle/gutter/index.ts
> +                disabled: window.siyuan.config.readonly,
相关的快捷键和其他菜单中的类似项也需要进行处理，须逐一核对。

2024-06-17 01:52 UTC, Vanessa219 commented on app/src/protyle/scroll/saveScroll.ts
>  export const getDocByScroll = (options: {
这个方法就是通过 scrollAttr 打开的，传入如果为空就没有意义了。这种场景是？

2024-06-17 01:52 UTC, Vanessa219 commented on app/src/util/assets.ts
> +            if (response.code === 0) {
参照第一点进行修改

2024-06-17 01:52 UTC, Vanessa219 commented on app/src/window/index.ts
> +        addBaseURL();
参照第二点进行修改

2024-06-18 15:29 UTC, Zuoqiu-Yingyi commented on app/src/config/editor.ts
> +                if (response.code === 0) {
用户在只读模式下打开设置面板后该请求会自动发出并返回异常, 因此需要额外处理一下

2024-06-18 15:29 UTC, Zuoqiu-Yingyi commented on app/src/index.ts
> +        addScriptSync(`${Constants.PROTYLE_CDN}/js/lute/lute.min.js?v=${Constants.SIYUAN_VERSION}`, "protyleLuteScript"),
这一块是为了与其他端调用顺序统一, 方便之后进行维护

2024-06-18 15:29 UTC, Zuoqiu-Yingyi commented on app/src/menus/commonMenuItem.ts
> +                        } else if (response.code === 0) {
此处更改是为了避免出现异常但仍推送成功消息提示

2024-06-18 15:29 UTC, Zuoqiu-Yingyi commented on app/src/protyle/gutter/index.ts
> +                disabled: window.siyuan.config.readonly,
如何禁用相关的快捷键?

目前已找到的其他菜单中的类似项已在只读模式下禁用，但不排除还有未找到的菜单项

2024-06-18 15:29 UTC, Zuoqiu-Yingyi commented on app/src/protyle/scroll/saveScroll.ts
>  export const getDocByScroll = (options: {
场景未知, 该问题是在发现控制台输出异常后定位到的
复现步骤: 只读/发布模式下刷新当前文档

2024-06-18 15:29 UTC, Zuoqiu-Yingyi commented on app/src/window/index.ts
> +        addBaseURL();
经过测试, 该方案正常工作, 且可以在 `Constants.PROTYLE_CDN` 变量发生更改时令脚本 `/js/lute/lute.min.js` 与 `/js/protyle-html.js` 加载行为与其他地方加载的 `/js/viewerjs/viewer.js` 等脚本一致, 增强健壮性

2024-06-20 09:38 UTC, TCOTC commented
啥时候能合并了发个 dev 版？

2024-06-21 14:32 UTC, Soltus commented
在线催更

2024-06-22 07:07 UTC, TCOTC commented
- @Zuoqiu-Yingyi 更改包含 #11788 吗？

2024-06-22 09:23 UTC, Zuoqiu-Yingyi commented
> - @Zuoqiu-Yingyi 更改包含 #11788 吗？

会禁用该菜单项

2024-06-24 01:49 UTC, JHPZ commented
我有个疑问，发布模式只能共享整个工作空间吗？假如我是Docker版，只有单个工作空间，它会把我想公布的和不想公布的都公布出去QAQ

2024-06-27 05:14 UTC, Zuoqiu-Yingyi commented
@Vanessa219 
该 PR 已经挂起 10 天了, 有无新的进展?

2024-07-02 08:20 UTC, aptexd commented
What happened? Is this still being tested?

2024-07-02 09:41 UTC, Jiangshuon commented
盲猜作者大佬需按V大要求进行修改后才能合并O(∩_∩)O

2024-07-03 05:51 UTC, Vanessa219 commented
看了下目前这个 PR 合并后还需要进行修改，等安排出修改的时间才能进行合并。

2024-07-04 05:46 UTC, Zuoqiu-Yingyi commented
> 看了下目前这个 PR 合并后还需要进行修改，等安排出修改的时间才能进行合并。

修改建议均进行了回复, 需要进一步讨论

2024-07-05 12:01 UTC, merged

2024-07-05 16:06 UTC, aptexd commented
Oh god, finally merged