✨ Add internal kernel API `/api/icon`
siyuan-note/siyuan pull request #12939
Opened 2024-10-27 09:52 UTC by Achuan-2

思源笔记内核添加`/api/icon`，使得思源笔记支持动态图标
![PixPin_2024-10-27_17-48-47](https://github.com/user-attachments/assets/226f3716-f170-4d5b-9af6-0eaee8533719)

## 参数

* `type`：图标类型，默认为1

  * `type=1`：显示年月日星期
  * `type=2`  **：**  显示年月日
  * `type=3`  **：**  仅显示年月
  * `type=4`  **：**  仅显示年
  * `type=5`  **：**  当前周数
  * `type=6`：仅返回星期
  * `type=7`：倒数日
  * `type=8`：文字图标
* `locale`：中英文切换，默认为cn，仅在type=1、2、3、5、6、7时有效

  * `locale=cn`：显示中文
  * `locale=en`：显示英文
* `color`：设置配色，一共八种配色
  * `color=red`
  * `color=blue`
  * `color=yellow`
  * `color=green`
  * `color=purple`
  * `color=pink`
  * `color=orange`
  * `color=grey`
  
![PixPin_2024-10-27_17-48-21](https://github.com/user-attachments/assets/9d19f0ca-44a7-4d70-9207-7f96a117595f)

* `date`: 设置日期，默认为当前日期，日期设置格式为`yyyy-mm-dd`，仅在type=1-7时有效
* `content`：设置文字图标的内容，默认为空，仅在type=8时有效

## 使用
`http://127.0.0.1:6806/api/icon`后添加type、color、locale、date/content等参数

## 示例

### type=1：显示年月日星期

默认显示今天的日期。

可通过`date=2024-10-26`指定显示的日期

![](https://fastly.jsdelivr.net/gh/Achuan-2/PicBed/assets/20241027142805-2024-10-27.png)

```markdown
![](http://127.0.0.1:6806/api/icon?color=red&locale=cn&date=2024-10-27)
![](http://127.0.0.1:6806/api/icon?color=red&locale=en&date=2024-10-27)
```

### type=2：显示年月日

![](https://fastly.jsdelivr.net/gh/Achuan-2/PicBed/assets/20241027142810-2024-10-27.png)

```markdown
![](http://127.0.0.1:6806/api/icon?type=2&color=red&locale=&date=2024-10-27)
![](http://127.0.0.1:6806/api/icon?type=2&color=red&locale=en&date=2024-10-27)
```

### **type=3**：仅显示年月

![](https://fastly.jsdelivr.net/gh/Achuan-2/PicBed/assets/20241027142822-2024-10-27.png)

```markdown
![](http://127.0.0.1:6806/api/icon?type=3&color=red&locale=cn&date=2024-10-27)
![](http://127.0.0.1:6806/api/icon?type=3&color=red&locale=en&date=2024-10-27)

```

### **type=4**：仅显示年

![](https://fastly.jsdelivr.net/gh/Achuan-2/PicBed/assets/20241027142832-2024-10-27.png)

```markdown
![](http://127.0.0.1:6806/api/icon?type=4&color=red&locale=cn&date=2024-10-27)
```

### type=5：当前周数

![](https://fastly.jsdelivr.net/gh/Achuan-2/PicBed/assets/20241027142842-2024-10-27.png)

```markdown
![](http://127.0.0.1:6806/api/icon?type=5&color=red&locale=cn&date=2024-10-27)

![](http://127.0.0.1:6806/api/icon?type=5&color=red&locale=en&date=2024-10-27)
```

### type=6：仅返回星期

不输入color的话，默认星期一到星期五为红色，星期六和星期日为蓝色

![](https://fastly.jsdelivr.net/gh/Achuan-2/PicBed/assets/20241027142857-2024-10-27.png)

```markdown
![](http://127.0.0.1:6806/api/icon?type=6&locale=en&date=2024-10-21 "星期一")

![](http://127.0.0.1:6806/api/icon?type=6&locale=en&date=2024-10-22 "星期二")

![](http://127.0.0.1:6806/api/icon?type=6&locale=en&date=2024-10-23 "星期三")

![](http://127.0.0.1:6806/api/icon?type=6&locale=en&date=2024-10-24 "星期四")

![](http://127.0.0.1:6806/api/icon?type=6&locale=en&date=2024-10-25 "星期五")

![](http://127.0.0.1:6806/api/icon?type=6&locale=en&date=2024-10-26 "星期六")

![](http://127.0.0.1:6806/api/icon?type=6&locale=en&date=2024-10-27 "星期日")
```

指定color

![](https://fastly.jsdelivr.net/gh/Achuan-2/PicBed/assets/20241027142906-2024-10-27.png)

```markdown
![](http://127.0.0.1:6806/api/icon?type=6&locale=en&date=2024-10-21&color=red "星期一")

![](http://127.0.0.1:6806/api/icon?type=6&locale=cn&date=2024-10-22&color=blue "星期二")

![](http://127.0.0.1:6806/api/icon?type=6&locale=cn&date=2024-10-23&color=green "星期三")

![](http://127.0.0.1:6806/api/icon?type=6&locale=cn&date=2024-10-24&color=yellow "星期四")

![](http://127.0.0.1:6806/api/icon?type=6&locale=cn&date=2024-10-25&color=purple "星期五")

![](http://127.0.0.1:6806/api/icon?type=6&locale=cn&date=2024-10-26&color=pink "星期六")

![](http://127.0.0.1:6806/api/icon?type=6&locale=cn&date=2024-10-27&color=grey "星期日")
```

### type=7：倒数日

该图标会显示当前日期与指定日期之间的天数。

支持 `locale=en` 修改为英文：

* `已过` 用 `Past` 表示。
* `还有` 用 `Left` 表示。

![](https://fastly.jsdelivr.net/gh/Achuan-2/PicBed/assets/20241027142922-2024-10-27.png)

```markdown
![](http://127.0.0.1:6806/api/icon?color=red&date=2024-10-22&type=7&locale=cn)
![](http://127.0.0.1:6806/api/icon?color=red&date=2024-10-22&type=7&locale=en)
```

![](https://fastly.jsdelivr.net/gh/Achuan-2/PicBed/assets/20241027142940-2024-10-27.png)

```markdown
![](http://127.0.0.1:6806/api/icon?color=red&type=7&locale=cn)
![](http://127.0.0.1:6806/api/icon?color=red&type=7&locale=en)
```

![](https://fastly.jsdelivr.net/gh/Achuan-2/PicBed/assets/PixPin_2024-10-27_14-30-03-2024-10-27.png)

```markdown
![](http://127.0.0.1:6806/api/icon?color=red&date=3035-10-26&type=7&locale=cn)
![](http://127.0.0.1:6806/api/icon?color=red&date=3035-10-26&type=7&locale=en)
```

### type=8：文字图标

该图标可以显示文字。

![](https://fastly.jsdelivr.net/gh/Achuan-2/PicBed/assets/20241027143019-2024-10-27.png)

```markdown
![](http://127.0.0.1:6806/api/icon?type=8&content=知乎&color=blue)
![](http://127.0.0.1:6806/api/icon?type=8&content=GREAT&color=red)
```

2024-10-27 10:03 UTC, wish5115 commented
大小怎么设置？

2024-10-27 10:06 UTC, Achuan-2 commented
> 大小怎么设置？

返回的就是svg，如果在笔记里放，拖动设置图片大小就可以了。

2024-10-27 10:07 UTC, 88250 requested changes

2024-10-27 10:07 UTC, 88250 commented on kernel/api/router.go
> +    	ginServer.Handle("GET", "/api/icon", getDynamicIcon) //  添加动态图标路由
建议修改地址，比如 `/api/icon/getDynamicIcon`

2024-10-27 10:07 UTC, 88250 commented on kernel/api/icon.go
> +
删掉多余的空行

2024-10-27 10:07 UTC, 88250 commented on kernel/api/icon.go
> +	locale := c.DefaultQuery("locale", "cn")
这里的参数作为可选值，默认值使用 `util.Lang`

2024-10-27 10:08 UTC, wish5115 commented
> > 大小怎么设置？
> 
> 返回的就是svg，如果在笔记里放，拖动设置图片大小就可以了。默认是512*512大小

哦哦

2024-10-27 10:29 UTC, Achuan-2 commented on kernel/api/router.go
> +    	ginServer.Handle("GET", "/api/icon", getDynamicIcon) //  添加动态图标路由
> 建议修改地址，比如 `/api/icon/getDynamicIcon`

之前是这样写的，但是为了更好记，就设置为/api/icon
如果D大觉得为了统一规范，我就改为 `/api/icon/getDynamicIcon`

2024-10-27 10:35 UTC, TCOTC commented on kernel/api/router.go
> +    	ginServer.Handle("GET", "/api/icon", getDynamicIcon) //  添加动态图标路由
我觉得 icon 也许还能再加功能，直接用 icon 就不灵活了

2024-10-27 11:46 UTC, Achuan-2 commented on kernel/api/router.go
> +    	ginServer.Handle("GET", "/api/icon", getDynamicIcon) //  添加动态图标路由
已修改

2024-10-27 11:46 UTC, Achuan-2 commented on kernel/api/icon.go
> +
已修改

2024-10-27 11:46 UTC, Achuan-2 commented on kernel/api/icon.go
> +	locale := c.DefaultQuery("locale", "cn")
已修改，现在支持繁体了
![PixPin_2024-10-27_19-46-17](https://github.com/user-attachments/assets/1b8657c7-bda1-4b11-8ef8-fa742d257d88)
![PixPin_2024-10-27_19-46-23](https://github.com/user-attachments/assets/ea79781f-8f4d-4f87-8865-7550f0b7ec84)
![PixPin_2024-10-27_19-46-28](https://github.com/user-attachments/assets/fdfa2ddd-fdbd-4988-aa5f-414b2e150374)

2024-10-27 11:51 UTC, TCOTC commented
我希望加一个 星期/周**天**

参考模板这个：

![image](https://github.com/user-attachments/assets/4e04843d-4c70-4961-97fa-1cf65391d944)

2024-10-27 13:40 UTC, 88250 requested changes

2024-10-27 13:40 UTC, 88250 commented on kernel/api/icon.go
> +	locale := c.DefaultQuery("locale", util.Lang)
这里的参数名统一使用 `lang` 吧，下面函数签名和变量名麻烦一并改一下。因为思源内部都是根据语言切换的。

2024-10-27 13:40 UTC, 88250 commented on kernel/api/icon.go
> +	case "en_US", "en_ES":
这里去掉吧，直接走下面的 default

2024-10-27 14:01 UTC, Achuan-2 commented on kernel/api/icon.go
> +	locale := c.DefaultQuery("locale", util.Lang)
> 参数名统一使用 lang 吧
这个指的是什么，locale我不是已经用util.Lang了吗，
现在已经可以根据语言更改图标语言了

2024-10-27 14:06 UTC, TCOTC commented on kernel/api/icon.go
> +	locale := c.DefaultQuery("locale", util.Lang)
我觉得是这个意思：locale → lang

2024-10-27 14:07 UTC, Achuan-2 commented on kernel/api/icon.go
> +	locale := c.DefaultQuery("locale", util.Lang)
> 这里的参数名统一使用 `lang` 吧，下面函数签名和变量名麻烦一并改一下。因为思源内部都是根据语言切换的。

指的是locale改为lang吗

2024-10-27 14:07 UTC, 88250 commented on kernel/api/icon.go
> +	locale := c.DefaultQuery("locale", util.Lang)
嗯，主要指的是参数的名称，改为 `lang`

2024-10-27 14:14 UTC, Achuan-2 commented on kernel/api/icon.go
> +	locale := c.DefaultQuery("locale", util.Lang)
> 嗯，主要指的是参数的名称，改为 `lang`

好滴，改好了

2024-10-27 14:16 UTC, Achuan-2 commented
> 我希望加一个 星期/周**天**
> 
> 参考模板这个：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/380492302-4e04843d-4c70-4961-97fa-1cf65391d944.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzg3ODMsIm5iZiI6MTczMDAzODQ4MywicGF0aCI6Ii83ODQzNDgyNy8zODA0OTIzMDItNGUwNDg0M2QtNGM3MC00OTYxLTk3ZmEtMWNmNjUzOTFkOTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDE0MTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNjFjOWE1YzliYTg2OTA3MTZjZWZkMjgzZjQzMzg1NTEwZmRlMjgxY2NkZDA5ZTRjMDYwZjJmZTJmZWIyYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hjUHCwg3AQJzt9lv2ZyZ1yJHPm_ic2Aflx5K0i6FVs4)

已经支持
![PixPin_2024-10-27_22-15-44](https://github.com/user-attachments/assets/815fe715-4d1a-4754-b57e-390e88d3728e)

2024-10-27 14:18 UTC, 88250 approved these changes

2024-10-27 14:20 UTC, merged

2024-10-27 14:20 UTC, 88250 commented
感谢你的贡献，思源有你更精彩！
Thank you for your contribution. SiYuan will be more wonderful with you!

2024-10-27 14:25 UTC, Achuan-2 commented
使用方法已经更新

2024-10-29 11:49 UTC, luo-chuan commented
本机使用和伺服使用的时候，图片链接中的 ip 不一致。

有没有办法使用 `siyuan://api/icon/xxxxxx` 这样的链接呢？

2024-10-29 11:54 UTC, Wetoria commented
> 本机使用和伺服使用的时候，图片链接中的 ip 不一致。
> 
> 有没有办法使用 `siyuan://api/icon/xxxxxx` 这样的链接呢？

img地址用 `api/icon/xxxxxx`

2024-11-08 03:56 UTC, Vanessa219 commented
@Achuan-2 color 需要支持一下变量，如 `var(--b3-card-warning-color)`

2024-11-08 08:19 UTC, Achuan-2 commented
> @Achuan-2
> 
> 1. color 需要支持一下变量，如 `var(--b3-card-warning-color)`
> 2. 能否全部类型都设置为正方形，即长和宽一致

1.color 需要支持一下变量，如 var(--b3-card-warning-color)

这个我感觉没必要，wolai的动态图标也是单独配色的，字体背景颜色、文字颜色不一定适合用来当图标颜色的，背景色会偏淡一点，文字颜色饱和度又会偏深。
另外go代码可以获取到 var(--b3-card-warning-color)的实际变量吗，是不是应该在前端调用http的时候就自动获取实际的值，然后再调用api

2. 能否全部类型都设置为正方形，即长和宽一致
更改viewbox就可以，我等会提交，之前设计的时候就是新建512×512的画布的，只不过导出的时候会有点点改变

2024-11-08 10:57 UTC, Vanessa219 commented
变量还是需要的，不同主题可以适配

2024-11-08 11:23 UTC, Achuan-2 commented
> 变量还是需要的，不同主题可以适配。不一定用 `var(--b3-card-warning-color)` 这个变量，可以用 `--b3-dynamic-emoji-color` 之类的

是可以搞一个单独的css变量，主题想改自己改（虽然我觉得图标不是文字，其实不同主题不太需要适配，都能比较好的显示，除非他觉得默认的配色不喜欢）

不过这个解析css变量的功能应该是前端js来做然后传递给内核吧，内核可以直接做吗，我不太了解。得v姐帮忙，或者指点我下。

2024-11-09 05:36 UTC, Vanessa219 commented
这样好像不会跟随系统
`api/icon/getDynamicIcon?type=2&color=red&date=2024-11-09&lang=`

只能用变量哦，比如一个主题选了 --b3-card-warning-color ，解析为 red，另外一个主题解析出来是 darkred，这个时候系统不会根据主题的切换去修改 emoji 的链接的。

把变量值换为我传给你的就可以了
![image](https://github.com/user-attachments/assets/259f9887-37e2-478e-b166-ee7b7df9c96e)

2024-11-09 05:43 UTC, Achuan-2 commented
> 这样好像不会跟随系统 `api/icon/getDynamicIcon?type=2&color=red&date=2024-11-09&lang=`
> 
> 只能用变量哦，比如一个主题选了 --b3-card-warning-color ，解析为 red，另外一个主题解析出来是 darkred，这个时候系统不会根据主题的切换去修改 emoji 的链接的。
> 
> 把变量值换为我传给你的就可以了 ![image](https://private-user-images.githubusercontent.com/970828/384580198-259f9887-37e2-478e-b166-ee7b7df9c96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzEwNDEsIm5iZiI6MTczMTEzMDc0MSwicGF0aCI6Ii85NzA4MjgvMzg0NTgwMTk4LTI1OWY5ODg3LTM3ZTItNDc4ZS1iMTY2LWVlN2I3ZGY5Yzk2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwNTM5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjQ4MDJmOWM1YWVkYzA1NTUzY2QxMTUxYTJmYzdiZTA1MjMwNTlmNTg1MTY4ZWM1OTNiYzVhNjliY2U2NDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JpXEdfCCSwHgUGMDGjFS60i-UdaDpLuLH8kj7OWZLG8)

svg直接用变量我试过了，目前不行的
因为思源目前用动态图片是用的链接显示，而不是svg直接加载到dom里，用链接显示的话，就没法传递css变量了

2024-11-09 07:39 UTC, Vanessa219 commented
好的，我也没找到合适的方法，就传色值吧

2024-11-24 10:12 UTC, luo-chuan commented
设置文档图标颜色时，可不可以用单词而不用色值呀？
![图片](https://github.com/user-attachments/assets/8755f912-27ac-458a-8c5d-d5392437d807)