Improve UserGuide
siyuan-note/siyuan pull request #13268
Opened 2024-11-25 15:12 UTC by emptylight370

日文使用机器翻译无法校对，仅重新翻译为中文大意不变。
可能存在潜在的数据问题，本地测试可正常打开，请校对。

## Feature or bug? 特性或者缺陷？

If you want to contribute a feature or bug fix, please submit an issue first. After a full discussion in the community, we will decide whether to make the change. Do not submit a contribution code directly, otherwise it may be rejected.
如果你想贡献一个特性或者缺陷修复，请先提交一个 issue。在社区充分讨论后，我们会决定是否进行变更。不要直接提交一个贡献代码，否则可能会被拒绝。

## Multilingual or copywriting? 多语言或者文案？

Please submit directly, we will evaluate.
请直接提交，我们会进行评估。

## Dev branch!

Any changes should be submitted to the dev branch.
任何改动，请提交到 dev 分支。

2024-11-25 15:17 UTC, TCOTC requested changes

2024-11-25 15:17 UTC, TCOTC commented on app/guide/20240530133126-axarxgx/20240530101000-4qitucx.sy
> +							"Data": "Siyuanを閉じると、ユーザーガイドは自動的に閉じられます。"
SiYuan 的 Y 大写

2024-11-25 15:18 UTC, emptylight370 commented
> 还是合并这个好了，我的日语忘记改成 SiYuan 了

我本地测试繁中和英文提示找不到[文档id]，我还在检查，先不合并

2024-11-25 15:19 UTC, TCOTC commented
这个正常，你没有重建索引就开始改了吧

2024-11-25 15:20 UTC, TCOTC commented
提交是没有问题的

2024-11-25 15:21 UTC, TCOTC commented on app/guide/20240530133126-axarxgx/20240530101000-4qitucx.sy
> +							"Data": "Siyuanを閉じると、ユーザーガイドは自動的に閉じられます。"
还有 SiYuan 之后要加个空格

2024-11-25 15:23 UTC, emptylight370 commented on app/guide/20240530133126-axarxgx/20240530101000-4qitucx.sy
> +							"Data": "Siyuanを閉じると、ユーザーガイドは自動的に閉じられます。"
已修改

2024-11-25 15:24 UTC, emptylight370 commented
对英文和日文的'Siyuan'改为'SiYuan'并添加必要的空格

2024-11-25 15:40 UTC, emptylight370 commented
将日文的引述符调至文本前，与其他语言保持一致

2024-11-26 03:51 UTC, merged

2024-11-26 03:51 UTC, 88250 commented
感谢你的贡献，思源有你更精彩！
Thank you for your contribution. SiYuan will be more wonderful with you!